import type { SessionUsage } from "../types";

interface TokenUsageBarProps {
  usage: SessionUsage | null;
}

/** Human-readable agent display names. */
const AGENT_LABELS: Record<string, string> = {
  orchestrator: "Orchestrator",
  librarian: "Librarian",
  "prose-writer": "Prose Writer",
  "narrative-director": "Narrative Director",
  "forge-planner": "Forge Planner",
  "forge-writer": "Forge Writer",
  "forge-reviewer": "Forge Reviewer",
  research: "Research",
};

function formatTokens(n: number): string {
  if (n >= 1_000_000) return `${(n / 1_000_000).toFixed(1)}M`;
  if (n >= 1_000) return `${(n / 1_000).toFixed(1)}k`;
  return String(n);
}

export default function TokenUsageBar({ usage }: TokenUsageBarProps) {
  const hasUsage = usage && usage.totalRequests > 0;
  const total = hasUsage ? usage.totalInput + usage.totalOutput : 0;

  return (
    <div className="flex flex-col gap-1 px-3 py-1.5 bg-surface border-t border-border text-[11px] text-text-muted shrink-0">
      {hasUsage ? (
        <>
          {/* Summary row */}
          <div className="flex items-center gap-3 font-mono tabular-nums">
            <span className="text-text-muted/60 uppercase tracking-wider text-[10px]">Session tokens</span>
            <span title="Input tokens (sent to LLM)">
              <span className="text-text-muted/40">in </span>
              {formatTokens(usage.totalInput)}
            </span>
            <span title="Output tokens (generated by LLM)">
              <span className="text-text-muted/40">out </span>
              {formatTokens(usage.totalOutput)}
            </span>
            <span title="Total tokens">
              <span className="text-text-muted/40">total </span>
              <span className="text-text/80">{formatTokens(total)}</span>
            </span>
            <span title="LLM API calls" className="text-text-muted/40">
              {usage.totalRequests} call{usage.totalRequests !== 1 ? "s" : ""}
            </span>
          </div>

          {/* Per-agent breakdown */}
          {usage.byAgent.length > 0 && (
            <div className="flex flex-wrap gap-x-3 gap-y-0.5 font-mono tabular-nums">
              {usage.byAgent.map((a) => {
                const agentTotal = a.input + a.output;
                return (
                  <span
                    key={a.agent}
                    title={`${a.agent}: ${a.input.toLocaleString()} in / ${a.output.toLocaleString()} out / ${a.requests} calls`}
                    className="inline-flex items-center gap-1"
                  >
                    <span className="text-accent/60">{AGENT_LABELS[a.agent] ?? a.agent}</span>
                    <span>{formatTokens(agentTotal)}</span>
                  </span>
                );
              })}
            </div>
          )}
        </>
      ) : (
        <div className="flex items-center gap-3 font-mono tabular-nums">
          <span className="text-text-muted/40 uppercase tracking-wider text-[10px]">Session tokens</span>
          <span className="text-text-muted/30">—</span>
        </div>
      )}
    </div>
  );
}
