using System.Text.Json;

namespace QuillForge.Core.Models;

/// <summary>
/// Events emitted during streaming completion. Abstract base with sealed derived types.
/// </summary>
public abstract class StreamEvent;

/// <summary>
/// Provider-facing transport facts observed while reading a streamed completion.
/// These events describe what the provider sent, not what QuillForge accepted.
/// </summary>
public abstract class TransportStreamEvent : StreamEvent;

/// <summary>
/// QuillForge-owned application facts produced while processing a streamed turn.
/// These events describe validated or app-generated behavior.
/// </summary>
public abstract class AppStreamEvent : StreamEvent;

/// <summary>
/// A chunk of text generated by the model.
/// </summary>
public sealed class TextDeltaEvent(string text) : TransportStreamEvent
{
    public string Text { get; } = text;
}

/// <summary>
/// A chunk of reasoning/thinking generated by the model.
/// </summary>
public sealed class ReasoningDeltaEvent(string text) : TransportStreamEvent
{
    public string Text { get; } = text;
}

/// <summary>
/// The provider emitted a tool-call delta payload.
/// When ParseError is non-null, the provider attempted a tool call but the
/// arguments were malformed or incomplete at the transport boundary.
/// </summary>
public sealed class ToolCallDeltaReceivedEvent(
    string toolName,
    string toolId,
    JsonElement input,
    string? parseError = null) : TransportStreamEvent
{
    public string ToolName { get; } = toolName;
    public string ToolId { get; } = toolId;
    public JsonElement Input { get; } = input;
    public string? ParseError { get; } = parseError;
}

/// <summary>
/// QuillForge accepted a tool call after boundary validation and is about to dispatch it.
/// The payload is no longer raw provider JSON; it is a validated tool-input envelope.
/// </summary>
public sealed class ToolCallValidatedEvent(string toolName, string toolId, ToolInput input) : AppStreamEvent
{
    public string ToolName { get; } = toolName;
    public string ToolId { get; } = toolId;
    public ToolInput Input { get; } = input;
}

/// <summary>
/// The streaming response is complete.
/// </summary>
public sealed class DoneEvent(StopReason stopReason, TokenUsage usage) : TransportStreamEvent
{
    public StopReason StopReason { get; } = stopReason;
    public TokenUsage Usage { get; } = usage;
    public ResponseType ResponseType { get; init; } = ResponseType.Discussion;

    /// <summary>
    /// QuillForge-owned replay envelope for adapter-specific round-tripping during streaming.
    /// Used by ReasoningCompletionService to preserve reasoning content and tool calls
    /// across tool loop rounds. Null for providers that don't need it.
    /// </summary>
    public ProviderReplayEnvelope? ProviderReplay { get; init; }
}

/// <summary>
/// A diagnostic entry for the live diagnostics panel.
/// Ephemeral display only — not persisted into sessions or chat history.
/// </summary>
public sealed class DiagnosticEvent(DiagnosticCategory category, string message, DiagnosticLevel level = DiagnosticLevel.Info) : AppStreamEvent
{
    public DiagnosticCategory Category { get; } = category;
    public string Message { get; } = message;
    public DiagnosticLevel Level { get; } = level;
}

/// <summary>
/// Categories for diagnostic events.
/// </summary>
public enum DiagnosticCategory
{
    /// <summary>Streaming lifecycle events.</summary>
    Stream,

    /// <summary>LLM call events.</summary>
    Llm,

    /// <summary>Tool dispatch and validation events.</summary>
    Tool,

    /// <summary>General warnings.</summary>
    Warning,
}

public enum DiagnosticLevel
{
    Info,
    Warning,
    Error,
}
