using System.Text.Json;

namespace QuillForge.Core.Models;

/// <summary>
/// Events emitted during streaming completion. Abstract base with sealed derived types.
/// </summary>
public abstract class StreamEvent;

/// <summary>
/// A chunk of text generated by the model.
/// </summary>
public sealed class TextDeltaEvent(string text) : StreamEvent
{
    public string Text { get; } = text;
}

/// <summary>
/// A chunk of reasoning/thinking generated by the model.
/// </summary>
public sealed class ReasoningDeltaEvent(string text) : StreamEvent
{
    public string Text { get; } = text;
}

/// <summary>
/// The model is invoking a tool.
/// </summary>
public sealed class ToolCallEvent(string toolName, string toolId, JsonElement input) : StreamEvent
{
    public string ToolName { get; } = toolName;
    public string ToolId { get; } = toolId;
    public JsonElement Input { get; } = input;
}

/// <summary>
/// The streaming response is complete.
/// </summary>
public sealed class DoneEvent(string stopReason, TokenUsage usage) : StreamEvent
{
    public string StopReason { get; } = stopReason;
    public TokenUsage Usage { get; } = usage;
}
